language: python
sudo: true  # Only required if PLANEMO_TEST_STYLE runs with Docker

python: 2.7
env:
  - WORKFLOW_TEST=example1/wf3-shed-tools.ga PLANEMO_TEST_STYLE=test
  - WORKFLOW_TEST=example1/wf3-shed-tools.ga PLANEMO_TEST_STYLE=docker_test
  - WORKFLOW_TEST=example1/wf3-shed-tools.ga PLANEMO_TEST_STYLE=serve_and_test
  - WORKFLOW_TEST=example1/wf3-shed-tools.ga PLANEMO_TEST_STYLE=docker_serve_and_test
  - WORKFLOW_TEST=example1/wf3-shed-tools.ga PLANEMO_TEST_STYLE=profile_serve_and_test

script: sh run_tests.sh "$WORKFLOW_TEST"

services:
  - postgresql  # Only required if PLANEMO_TEST_STYLE runs without Docker
  - docker      # Only required if PLANEMO_TEST_STYLE runs with Docker
